name: Test execution

on: [ push, pull_request, workflow_dispatch ]

permissions:
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: npm install
      - name: Run smoke tests
        run: |
          npx codeceptjs run --grep "@smoke" --override '{"helpers": {"Playwright": {"show": false}}}' --reporter mocha-junit-reporter
      - name: "Upload smoke test report artifact"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: smoke-test-report
          path: "**/output/test-report.xml"
      - name: Publish smoke report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          artifact: smoke-test-report
          name: Smoke tests
          path: "**/output/test-report.xml"
          reporter: java-junit
      - name: Run regression tests
        if: always()
        run: |
          npx codeceptjs run --grep "@regression" --override '{"helpers": {"Playwright": {"show": false}}}' --reporter mocha-junit-reporter
      - name: "Upload regression test report artifact"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: regression-test-report
          path: "**/output/test-report.xml"
      - name: Publish regression report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          artifact: regression-test-report
          name: Regression tests
          path: "**/output/test-report.xml"
          reporter: java-junit